/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uninorte.ospedale.view;

import com.uninorte.ospedale.controller.ComboDataController;
import com.uninorte.ospedale.controller.DoctorController;
import com.uninorte.ospedale.controller.PatientController;
import com.uninorte.ospedale.controller.TableDataController;
import java.awt.Color;
import com.uninorte.ospedale.model.dto.DoctorFormDTO;
import com.uninorte.ospedale.model.dto.PatientFormDTO;
import com.uninorte.ospedale.model.dto.UserSessionDTO;
import com.uninorte.ospedale.model.enums.Role;
import com.uninorte.ospedale.view.navigation.ViewNavigator;
import com.uninorte.ospedale.controller.response.Response;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class AdminView extends javax.swing.JFrame {

    private int x, y;
    private final DoctorController doctorController;
    private final PatientController patientController;
    private final ComboDataController comboController;
    private final TableDataController tableController;
    private final ViewNavigator navigator;
    private final UserSessionDTO session;
    private final java.util.List<Long> doctorComboIds = new java.util.ArrayList<>();
    private final java.util.List<Long> patientComboIds = new java.util.ArrayList<>();
    public AdminView(
        DoctorController doctorController,
        PatientController patientController,
        ComboDataController comboController,
        TableDataController tableController,
        ViewNavigator navigator,
        UserSessionDTO session
) {

    this.doctorController = doctorController;
    this.patientController = patientController;
    this.comboController = comboController;
    this.tableController = tableController;
    this.navigator = navigator;
    this.session = session;

    initComponents();

    this.setBackground(new Color(0, 0, 0, 0));
    this.setLocationRelativeTo(null);

    loadCombos();
}
    
   private void loadCombos() {
    txtDocPassword.setText("");
    txtDocPasswordConfirm.setText("");
    @SuppressWarnings("unchecked")
    java.util.List<String> specialties = (java.util.List<String>) comboController.getSpecialties().data;
    cmbDocSpecialty.setModel(new DefaultComboBoxModel<>(
        specialties.toArray(new String[0])
    ));

    @SuppressWarnings("unchecked")
    java.util.List<String[]> doctors = (java.util.List<String[]>) comboController.getDoctors().data;
    doctorComboIds.clear();
    java.util.List<String> doctorItems = new java.util.ArrayList<>();
    doctorItems.add("Select one");
    for (String[] d : doctors) {
        doctorComboIds.add(Long.parseLong(d[0]));
        doctorItems.add(d[1]);
    }
    cmbSelectDoctor.setModel(new DefaultComboBoxModel<>(doctorItems.toArray(new String[0])));

    @SuppressWarnings("unchecked")
    java.util.List<String> patients = (java.util.List<String>) comboController.getPatientsCombo().data;
    patientComboIds.clear();
    java.util.List<String> patientItems = new java.util.ArrayList<>();
    patientItems.add("Select one");
    for (String item : patients) {
        String[] parts = item.split(" - ", 2);
        patientComboIds.add(Long.parseLong(parts[0].trim()));
        patientItems.add(parts.length > 1 ? parts[1] : item);
    }
    cmbSelectPatient.setModel(new DefaultComboBoxModel<>(patientItems.toArray(new String[0])));
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new packagee.PanelRound();
        pnlTopbar = new packagee.PanelRound();
        btnClose = new javax.swing.JButton();
        lblAdminTitle = new javax.swing.JLabel();
        pnlCard = new packagee.PanelRound();
        btnGoDoctorView = new javax.swing.JButton();
        btnGoPatientView = new javax.swing.JButton();
        lblDocFirstname = new javax.swing.JLabel();
        txtDocFirstname = new javax.swing.JTextField();
        lblDocLastname = new javax.swing.JLabel();
        txtDocLastname = new javax.swing.JTextField();
        lblDocId = new javax.swing.JLabel();
        txtDocId = new javax.swing.JTextField();
        lblDocSpecialty = new javax.swing.JLabel();
        lblDocLicenceNumber = new javax.swing.JLabel();
        txtDocLicenceNumber = new javax.swing.JTextField();
        lblDocOffice = new javax.swing.JLabel();
        txtDocOffice = new javax.swing.JTextField();
        lblDocUsername = new javax.swing.JLabel();
        txtDocUsername = new javax.swing.JTextField();
        lblDocPassword = new javax.swing.JLabel();
        lblDocPasswordConfirm = new javax.swing.JLabel();
        cmbDocSpecialty = new javax.swing.JComboBox<>();
        btnRegisterDoctor = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbSelectDoctor = new javax.swing.JComboBox<>();
        lblSelectDoctor = new javax.swing.JLabel();
        lblSelectPatient = new javax.swing.JLabel();
        cmbSelectPatient = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        txtDocPassword = new javax.swing.JPasswordField();
        txtDocPasswordConfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setRadius(50);

        pnlTopbar.setRadius(50);
        pnlTopbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopbarMouseDragged(evt);
            }
        });
        pnlTopbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopbarMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblAdminTitle.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblAdminTitle.setText("ADMIN VIEW");

        javax.swing.GroupLayout pnlTopbarLayout = new javax.swing.GroupLayout(pnlTopbar);
        pnlTopbar.setLayout(pnlTopbarLayout);
        pnlTopbarLayout.setHorizontalGroup(
            pnlTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopbarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAdminTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        pnlTopbarLayout.setVerticalGroup(
            pnlTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAdminTitle))
        );

        btnGoDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGoDoctorView.setText("DOCTOR VIEW");
        btnGoDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoDoctorViewActionPerformed(evt);
            }
        });

        btnGoPatientView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnGoPatientView.setText("PATIENT VIEW");
        btnGoPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPatientViewActionPerformed(evt);
            }
        });

        lblDocFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocFirstname.setText("Firstname");

        txtDocFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocLastname.setText("Lastname");

        txtDocLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocId.setText("ID");

        txtDocId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocSpecialty.setText("Specialty");

        lblDocLicenceNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocLicenceNumber.setText("License Number");

        txtDocLicenceNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocOffice.setText("Assigned office");

        txtDocOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocUsername.setText("User");

        txtDocUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblDocPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocPassword.setText("Password");

        lblDocPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblDocPasswordConfirm.setText("Password confirmation");

        cmbDocSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbDocSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnRegisterDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterDoctor.setText("Save");
        btnRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDoctorActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbSelectDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSelectDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        lblSelectDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSelectDoctor.setText("Doctor");

        lblSelectPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblSelectPatient.setText("Patient");

        cmbSelectPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbSelectPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtDocPassword.setText("jPasswordField1");

        txtDocPasswordConfirm.setText("jPasswordField2");

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnRegisterDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDocFirstname)
                                    .addComponent(lblDocSpecialty))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCardLayout.createSequentialGroup()
                                        .addComponent(cmbDocSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDocLicenceNumber)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocLicenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlCardLayout.createSequentialGroup()
                                        .addComponent(txtDocFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lblDocLastname)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDocId)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addComponent(lblDocOffice)
                                .addGap(18, 18, 18)
                                .addComponent(txtDocOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlCardLayout.createSequentialGroup()
                                    .addComponent(lblDocUsername)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDocUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlCardLayout.createSequentialGroup()
                                    .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDocPasswordConfirm)
                                        .addComponent(lblDocPassword))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDocPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(txtDocPasswordConfirm)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoDoctorView)
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmbSelectDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblSelectDoctor)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(318, 318, 318)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGoPatientView)
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cmbSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblSelectPatient)))
                .addGap(88, 88, 88))
            .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocFirstname)
                    .addComponent(txtDocFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocLastname)
                    .addComponent(txtDocLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocId)
                    .addComponent(txtDocId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocSpecialty)
                    .addComponent(cmbDocSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocLicenceNumber)
                    .addComponent(txtDocLicenceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDocOffice)
                    .addComponent(txtDocOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocUsername)
                            .addComponent(txtDocUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocPassword)
                            .addComponent(txtDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblDocPasswordConfirm))
                            .addGroup(pnlCardLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDocPasswordConfirm))))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblSelectDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSelectDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnGoDoctorView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnRegisterDoctor)
                .addGap(123, 123, 123)
                .addComponent(btnLogout)
                .addGap(38, 38, 38))
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(lblSelectPatient)
                .addGap(18, 18, 18)
                .addComponent(cmbSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnGoPatientView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator2)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlTopbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTopbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopbarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTopbarMousePressed

    private void pnlTopbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopbarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlTopbarMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
navigator.exit();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDoctorActionPerformed
       DoctorFormDTO dto = new DoctorFormDTO(
        txtDocId.getText(),
        txtDocUsername.getText(),
        txtDocFirstname.getText(),
        txtDocLastname.getText(),
        new String(txtDocPassword.getPassword()),
        new String(txtDocPasswordConfirm.getPassword()),
        (String) cmbDocSpecialty.getSelectedItem(),
        txtDocLicenceNumber.getText(),
        txtDocOffice.getText()
);

Response<?> r = doctorController.register(dto);

JOptionPane.showMessageDialog(this, r.message);

if (r.code == 200) {

    txtDocId.setText("");
    txtDocUsername.setText("");
    txtDocFirstname.setText("");
    txtDocLastname.setText("");
    txtDocPassword.setText("");
    txtDocPasswordConfirm.setText("");
    txtDocLicenceNumber.setText("");
    txtDocOffice.setText("");
}
    }//GEN-LAST:event_btnRegisterDoctorActionPerformed

    private void btnGoDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoDoctorViewActionPerformed
        int idx = cmbSelectDoctor.getSelectedIndex() - 1;
        if (idx < 0 || idx >= doctorComboIds.size()) {
            JOptionPane.showMessageDialog(this, "Seleccione un médico");
            return;
        }
        long doctorId = doctorComboIds.get(idx);
        Response<DoctorFormDTO> resp = doctorController.getProfile(doctorId);
        if (resp.getCode() != 200) {
            JOptionPane.showMessageDialog(this, resp.getMessage());
            return;
        }
        DoctorFormDTO dto = resp.getData();
        UserSessionDTO doctorSession = new UserSessionDTO(
                doctorId, dto.username(), dto.firstname(), dto.lastname(), Role.DOCTOR);
        navigator.openDoctorAsAdmin(doctorSession);
    }//GEN-LAST:event_btnGoDoctorViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
       navigator.logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGoPatientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPatientViewActionPerformed
        int idx = cmbSelectPatient.getSelectedIndex() - 1;
        if (idx < 0 || idx >= patientComboIds.size()) {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente");
            return;
        }
        long patientId = patientComboIds.get(idx);
        Response<PatientFormDTO> resp = patientController.getProfile(patientId);
        if (resp.getCode() != 200) {
            JOptionPane.showMessageDialog(this, resp.getMessage());
            return;
        }
        PatientFormDTO dto = resp.getData();
        UserSessionDTO patientSession = new UserSessionDTO(
                patientId, dto.username(), dto.firstname(), dto.lastname(), Role.PATIENT);
        navigator.openPatientAsAdmin(patientSession);
    }//GEN-LAST:event_btnGoPatientViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGoDoctorView;
    private javax.swing.JButton btnGoPatientView;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegisterDoctor;
    private javax.swing.JComboBox<String> cmbDocSpecialty;
    private javax.swing.JComboBox<String> cmbSelectDoctor;
    private javax.swing.JComboBox<String> cmbSelectPatient;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdminTitle;
    private javax.swing.JLabel lblDocFirstname;
    private javax.swing.JLabel lblDocId;
    private javax.swing.JLabel lblDocLastname;
    private javax.swing.JLabel lblDocLicenceNumber;
    private javax.swing.JLabel lblDocOffice;
    private javax.swing.JLabel lblDocPassword;
    private javax.swing.JLabel lblDocPasswordConfirm;
    private javax.swing.JLabel lblDocSpecialty;
    private javax.swing.JLabel lblDocUsername;
    private javax.swing.JLabel lblSelectDoctor;
    private javax.swing.JLabel lblSelectPatient;
    private packagee.PanelRound pnlCard;
    private packagee.PanelRound pnlRoot;
    private packagee.PanelRound pnlTopbar;
    private javax.swing.JTextField txtDocFirstname;
    private javax.swing.JTextField txtDocId;
    private javax.swing.JTextField txtDocLastname;
    private javax.swing.JTextField txtDocLicenceNumber;
    private javax.swing.JTextField txtDocOffice;
    private javax.swing.JPasswordField txtDocPassword;
    private javax.swing.JPasswordField txtDocPasswordConfirm;
    private javax.swing.JTextField txtDocUsername;
    // End of variables declaration//GEN-END:variables
}
