/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uninorte.ospedale.view;

import com.uninorte.ospedale.controller.PatientController;
import com.uninorte.ospedale.model.dto.PatientFormDTO;
import com.uninorte.ospedale.controller.AuthController;
import com.uninorte.ospedale.controller.response.Response;
import com.uninorte.ospedale.model.dto.UserSessionDTO;
import com.uninorte.ospedale.view.navigation.ViewNavigator;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author jjlora
 * @author edangulo
 */
public class LoginView extends javax.swing.JFrame {

    private int x, y;
    private final AuthController authController;
    private final PatientController patientController;
    private final ViewNavigator navigator;

        public LoginView(AuthController authController,PatientController patientController, ViewNavigator navigator) {
        this.authController = authController;
        this.patientController = patientController;
        this.navigator = navigator;
        initComponents();

        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new packagee.PanelRound();
        pnlTopbar = new packagee.PanelRound();
        btnClose = new javax.swing.JButton();
        tabsLoginRegister = new javax.swing.JTabbedPane();
        pnlCard = new packagee.PanelRound();
        lblLoginTitle = new javax.swing.JLabel();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblRegFirstname = new javax.swing.JLabel();
        txtRegFirstname = new javax.swing.JTextField();
        lblRegLastname = new javax.swing.JLabel();
        txtRegLastname = new javax.swing.JTextField();
        lblRegId = new javax.swing.JLabel();
        txtRegId = new javax.swing.JTextField();
        lblRegGender = new javax.swing.JLabel();
        lblRegPhone = new javax.swing.JLabel();
        txtRegPhone = new javax.swing.JTextField();
        lblRegEmail = new javax.swing.JLabel();
        txtRegEmail = new javax.swing.JTextField();
        lblRegUsername = new javax.swing.JLabel();
        txtRegUsername = new javax.swing.JTextField();
        txtRegPassword = new javax.swing.JTextField();
        lblRegPassword = new javax.swing.JLabel();
        lblRegPasswordConfirm = new javax.swing.JLabel();
        txtRegPasswordConfirm = new javax.swing.JTextField();
        cmbRegGender = new javax.swing.JComboBox<>();
        btnRegisterPatient = new javax.swing.JButton();
        lblRegAddress = new javax.swing.JLabel();
        txtRegAddress = new javax.swing.JTextField();
        lblRegBirthdate = new javax.swing.JLabel();
        txtRegBirthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlRoot.setRadius(50);

        pnlTopbar.setRadius(50);
        pnlTopbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlTopbarMouseDragged(evt);
            }
        });
        pnlTopbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTopbarMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopbarLayout = new javax.swing.GroupLayout(pnlTopbar);
        pnlTopbar.setLayout(pnlTopbarLayout);
        pnlTopbarLayout.setHorizontalGroup(
            pnlTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        pnlTopbarLayout.setVerticalGroup(
            pnlTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblLoginTitle.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblLoginTitle.setText("LOGIN");

        txtLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginUsername.setText("USERNAME");

        txtLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLoginPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLoginPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblLoginPassword.setText("PASSWORD");

        btnLogin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogin.setText("ENTER");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCardLayout = new javax.swing.GroupLayout(pnlCard);
        pnlCard.setLayout(pnlCardLayout);
        pnlCardLayout.setHorizontalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(lblLoginTitle)
                .addGap(481, 481, 481))
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createSequentialGroup()
                                .addGroup(pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLoginUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlCardLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCardLayout.setVerticalGroup(
            pnlCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLoginTitle)
                .addGap(74, 74, 74)
                .addComponent(lblLoginUsername)
                .addGap(18, 18, 18)
                .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword)
                .addGap(18, 18, 18)
                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLogin)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tabsLoginRegister.addTab("Login", pnlCard);

        lblRegFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegFirstname.setText("Firstname");

        txtRegFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegLastname.setText("Lastname");

        txtRegLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegId.setText("ID");

        txtRegId.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegGender.setText("Gender");

        lblRegPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegPhone.setText("Phone");

        txtRegPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegEmail.setText("Email");

        txtRegEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegUsername.setText("User");

        txtRegUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtRegPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        lblRegPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegPassword.setText("Password");

        lblRegPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegPasswordConfirm.setText("Password confirmation");

        txtRegPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRegPasswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegPasswordConfirmActionPerformed(evt);
            }
        });

        cmbRegGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cmbRegGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnRegisterPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRegisterPatient.setText("Save");
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        lblRegAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegAddress.setText("Address");

        txtRegAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRegAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegAddressActionPerformed(evt);
            }
        });

        lblRegBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblRegBirthdate.setText("Birthdate");

        txtRegBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRegBirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegBirthdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(lblRegPassword))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(lblRegUsername))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(txtRegPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnRegisterPatient))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(lblRegPasswordConfirm))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblRegBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRegBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblRegFirstname)
                                .addGap(34, 34, 34)
                                .addComponent(txtRegFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegLastname)
                            .addComponent(lblRegAddress))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRegLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegId)
                                .addGap(30, 30, 30)
                                .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegGender)
                                .addGap(26, 26, 26)
                                .addComponent(cmbRegGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegPhone)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRegEmail)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegFirstname)
                    .addComponent(txtRegFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegLastname)
                    .addComponent(txtRegLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegId)
                    .addComponent(txtRegId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegGender)
                    .addComponent(cmbRegGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegBirthdate)
                        .addComponent(txtRegBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegAddress)
                        .addComponent(txtRegAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegPhone)
                        .addComponent(txtRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegEmail)
                        .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(lblRegUsername)
                .addGap(18, 18, 18)
                .addComponent(txtRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegPassword)
                .addGap(18, 18, 18)
                .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegPasswordConfirm)
                .addGap(18, 18, 18)
                .addComponent(txtRegPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRegisterPatient)
                .addGap(42, 42, 42))
        );

        tabsLoginRegister.addTab("Patient register", jPanel3);

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTopbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(tabsLoginRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRootLayout.createSequentialGroup()
                .addComponent(pnlTopbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabsLoginRegister)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTopbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopbarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_pnlTopbarMousePressed
 
    private void pnlTopbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTopbarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x,
                this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_pnlTopbarMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String username = txtLoginUsername.getText();
    String password = txtLoginPassword.getText(); 

    Response<UserSessionDTO> response = authController.login(username, password);

    if (response.code != 200) {
    JOptionPane.showMessageDialog(this, response.message, "Login",
        JOptionPane.WARNING_MESSAGE);
    return;
    }

    navigator.routeAfterLogin(response.data);
    this.dispose();

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
            PatientFormDTO dto = new PatientFormDTO(
        txtRegId.getText(),
        txtRegUsername.getText(),
        txtRegFirstname.getText(),
        txtRegLastname.getText(),
        txtRegPassword.getText(),
        txtRegPasswordConfirm.getText(),
        txtRegEmail.getText(),
        txtRegBirthdate.getText(),
        (String) cmbRegGender.getSelectedItem(),
        txtRegPhone.getText(),
        txtRegAddress.getText()
    );

    Response<?> r = patientController.register(dto);
    JOptionPane.showMessageDialog(this, r.message);

    if (r.code == 200) {
        txtRegFirstname.setText("");
        txtRegLastname.setText("");
        txtRegId.setText("");
        txtRegPhone.setText("");
        txtRegEmail.setText("");
        txtRegUsername.setText("");
        txtRegPassword.setText("");
        txtRegPasswordConfirm.setText("");
        txtRegAddress.setText("");
        txtRegBirthdate.setText("");
        cmbRegGender.setSelectedIndex(0);
    }
    }//GEN-LAST:event_btnRegisterPatientActionPerformed

    private void txtRegPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegPasswordConfirmActionPerformed
    }//GEN-LAST:event_txtRegPasswordConfirmActionPerformed

    private void txtRegAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegAddressActionPerformed
    }//GEN-LAST:event_txtRegAddressActionPerformed

    private void txtRegBirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegBirthdateActionPerformed
    }//GEN-LAST:event_txtRegBirthdateActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JComboBox<String> cmbRegGender;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JLabel lblRegAddress;
    private javax.swing.JLabel lblRegBirthdate;
    private javax.swing.JLabel lblRegEmail;
    private javax.swing.JLabel lblRegFirstname;
    private javax.swing.JLabel lblRegGender;
    private javax.swing.JLabel lblRegId;
    private javax.swing.JLabel lblRegLastname;
    private javax.swing.JLabel lblRegPassword;
    private javax.swing.JLabel lblRegPasswordConfirm;
    private javax.swing.JLabel lblRegPhone;
    private javax.swing.JLabel lblRegUsername;
    private packagee.PanelRound pnlCard;
    private packagee.PanelRound pnlRoot;
    private packagee.PanelRound pnlTopbar;
    private javax.swing.JTabbedPane tabsLoginRegister;
    private javax.swing.JTextField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    private javax.swing.JTextField txtRegAddress;
    private javax.swing.JTextField txtRegBirthdate;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JTextField txtRegFirstname;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txtRegLastname;
    private javax.swing.JTextField txtRegPassword;
    private javax.swing.JTextField txtRegPasswordConfirm;
    private javax.swing.JTextField txtRegPhone;
    private javax.swing.JTextField txtRegUsername;
    // End of variables declaration//GEN-END:variables
}
